wandb_version: 1

learning_rate:
  desc: null
  value: 5.0e-05
architecture:
  desc: null
  value: efficientnet_b4
dataset:
  desc: null
  value: Tu Dataset Local
unfreezed_layers:
  desc: null
  value: 15
epochs:
  desc: null
  value: 20
batch_size:
  desc: null
  value: 64
_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1712999879.0
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.11.5
      5: 0.16.6
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
